# Generated by Django 2.2.18 on 2022-05-04 19:44

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=50)),
                ('feature_description', models.TextField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'FeatureQuestion',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('messenger', models.TextField()),
                ('phone_number', models.TextField()),
                ('email', models.CharField(max_length=75)),
            ],
            options={
                'verbose_name_plural': 'Feedback',
            },
        ),
        migrations.CreateModel(
            name='QualificationQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=150)),
                ('answer_variants', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=100), size=None)),
                ('is_multiple', models.BooleanField(null=True)),
            ],
            options={
                'verbose_name_plural': 'QualificationQuestion',
            },
        ),
        migrations.CreateModel(
            name='Questionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Form', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Questionary',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='questionary.Feedback')),
                ('questionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionary.Questionary')),
            ],
            options={
                'verbose_name_plural': 'Response',
            },
        ),
        migrations.CreateModel(
            name='QualificationResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_answers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualification_answers', to='questionary.Response')),
                ('qualification_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionary.QualificationQuestion')),
            ],
            options={
                'verbose_name_plural': 'QualificationResponse',
            },
        ),
        migrations.AddField(
            model_name='qualificationquestion',
            name='questionary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionary.Questionary'),
        ),
        migrations.CreateModel(
            name='FeatureResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_1', models.IntegerField()),
                ('answer_2', models.IntegerField()),
                ('answer_3', models.IntegerField()),
                ('feature_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionary.FeatureQuestion')),
                ('features_answers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features_answers', to='questionary.Response')),
            ],
            options={
                'verbose_name_plural': 'FeatureResponse',
            },
        ),
        migrations.AddField(
            model_name='featurequestion',
            name='questionary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_questions', to='questionary.Questionary'),
        ),
    ]
