# Generated by Django 2.2.18 on 2022-05-24 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualificationquestion',
            name='questionary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualification_questions', to='questionary.Questionary'),
        ),
    ]
