# Generated by Django 2.2.18 on 2022-07-07 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionary', '0003_auto_20220707_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualificationquestion',
            name='created_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 7, 16, 19, 29, 808854)),
        ),
    ]
