# Generated by Django 2.2.18 on 2022-07-07 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questionary', '0004_auto_20220707_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualificationquestion',
            name='created_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
