# Generated by Django 2.2.18 on 2022-07-08 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionary', '0007_auto_20220708_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureresponse',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_response', to='questionary.Response'),
        ),
        migrations.AlterField(
            model_name='qualificationresponse',
            name='response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualification_response', to='questionary.Response'),
        ),
    ]
