# Generated by Django 2.2.18 on 2022-07-09 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionary', '0008_auto_20220708_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='questionary',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='questionary.Questionary'),
        ),
    ]
