# Generated by Django 2.2.18 on 2022-07-09 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionary', '0010_auto_20220709_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='feedback',
        ),
        migrations.AddField(
            model_name='feedback',
            name='response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questionary.Response'),
        ),
    ]
