# Generated by Django 2.2.18 on 2022-07-09 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionary', '0011_auto_20220709_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='questionary.Response'),
        ),
    ]
