# Generated by Django 2.2.18 on 2022-08-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionary', '0013_auto_20220728_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureresponse',
            name='answer_1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='featureresponse',
            name='answer_2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='questionary',
            name='name',
            field=models.CharField(default='My Form', max_length=51),
        ),
    ]
